"""News articles and events for the Christiana High School volume test."""

from __future__ import annotations

from christiana_volume_copy import rich_html, paragraphs_to_html, word_count, IMAGES, u


def img(index: int) -> str:
    return u(IMAGES[index]["file"])


def img_alt(index: int) -> str:
    return IMAGES[index]["alt"]


def _long_block(topic_paras: list[str]) -> list[str]:
    return topic_paras


NEWS = [
    {
        "slug": "christiana-high-welcomes-students-new-academic-year",
        "title": "Christiana High Welcomes Students for the New Academic Year",
        "excerpt": "Christiana High School opened the academic year with assembly, new timetables and a charge to students to wear the uniform with purpose.",
        "category": "Announcements",
        "author": "Communications Office",
        "date": "2025-09-08",
        "featured": True,
        "home": True,
        "priority": 2,
        "image": 16,
        "length": "long",
        "content": rich_html(
            lead="Christiana High School opened its gates for a new academic year with the mix of nerves, new shoes and familiar house songs that mark September in a Jamaican high school. Prefects stood at the entrance. Teachers collected form lists. The assembly ground filled until the last rural bus arrived and the latecomers slipped into rows already humming with talk.",
            heading="A charge from the Principal",
            paras=[
                "Dr. Marsha Campbell told students that the year would be measured not only by CSEC and CAPE entries but by whether classrooms stayed orderly, whether homework was done, and whether younger students were looked after. She quoted the motto — Our Best Jamaica Hope — and asked the school to treat it as a daily practice rather than a line on a crest.",
                "Vice Principal Andre Williams reviewed the academic calendar: diagnostic tests in the lower school, coursework deadlines for Grade 10 and 11, and a sixth-form seminar series that will begin before the Christmas break. Parents were reminded that consultation evenings are not optional theatre. They are how a large school stays personal.",
            ],
            bullets=[
                "Form teachers issued timetables and codes of conduct before first period",
                "New Grade 7 students completed a campus orientation with prefects",
                "The library and computer laboratory posted opening hours on the notice board",
                "Sports trials were announced for football, netball and track",
            ],
            quote="A clean uniform and a finished exercise book are not small things. They are how a student tells this school, and this country, that they intend to be taken seriously. — Dr. Marsha Campbell",
            heading2="Settling into the work",
            more=[
                "The first week is always a negotiation between excitement and systems. Christiana High School used it to reset attendance procedures, to introduce new staff, and to remind returning students that last year’s habits travel with them. Grade 11 form rooms were quieter than Grade 7’s, as candidates began to feel the weight of the examination year.",
                "The English and mathematics departments scheduled extra diagnostic lessons for students who missed the July summer programme. Science teachers checked laboratory inventories. The guidance office posted a sign-up sheet for students who wanted an early conversation about subject combinations. None of this makes a headline in a national paper. All of it decides whether September becomes a foundation or a lost month.",
                "On the field, Mr. Omar Bennett ran fitness tests that produced the usual mixture of groans and secret pride. In the performing arts room, Mr. Jermaine Powell collected names for the choir before anyone could claim they were too busy. The technology club pinned a poster about a digital skills initiative that will run through the first term. The school was, in the best sense, noisy with intention.",
                "Parents who came through the office asked practical questions: Can my child stay for extra lessons? When is the first fee payment due? Who is the form teacher? Ms. Kimberly Vassell answered with the patience of someone who has opened a hundred files before lunch. The bursar’s window stayed open later than usual. A high school that serves farming and trading families cannot pretend that everyone arrives with the same morning.",
                "By Friday, the campus had a rhythm again. The late bell still caught a few students at the tuck shop. A Grade 8 class lost a textbook and found it in the library. A prefect wrote a first detention list that was shorter than last September’s, which Mrs. Simone Brown noted without celebrating too loudly. Opening week is a test of tone. Christiana High School tried to set one that was firm, welcoming and busy.",
                "The year ahead will include sports day, Jamaica Day, career conversations, mock examinations and the long walk toward May/June. None of those events will matter if the ordinary Tuesdays are wasted. That was the quiet message of the first assembly: begin well, stay well, and let the crest on your shirt mean something when you walk through Christiana after school.",
                "Teachers used form time to collect contact numbers, to check who still needed a house shirt, and to talk about phones, punctuality and the difference between a joke and humiliation. Those conversations are easy to skip. They are also how a school prevents September from becoming a month of small injuries that harden by Christmas.",
                "Alumni who happened to be in town stopped at the gate to watch assembly, a reminder that the audience for a new academic year is wider than the roll. Christiana High School begins again each September because the town keeps sending its children, and because the staff keep agreeing to meet them. The work of the year starts there, on an ordinary Monday, with a hymn, a register and a timetable that still smells of toner.",
            ],
        ),
    },
    {
        "slug": "grade-11-students-begin-csec-preparation-programme",
        "title": "Grade 11 Students Begin CSEC Preparation Programme",
        "excerpt": "Christiana High School has launched a structured CSEC preparation programme for Grade 11, combining extra lessons, past-paper clinics and SBA checkpoints.",
        "category": "Academic",
        "author": "Academic Affairs",
        "date": "2025-10-14",
        "featured": False,
        "home": True,
        "priority": 0,
        "image": 1,
        "length": "long",
        "content": rich_html(
            lead="Grade 11 at Christiana High School has moved from the general work of fourth form into the narrower, more anxious labour of CSEC preparation. The school has launched a programme that tries to make that labour visible: a published extra-lesson timetable, past-paper clinics, SBA checkpoints and a guidance conversation for every candidate who is still changing subjects in October.",
            heading="What the programme includes",
            paras=[
                "Mr. Andre Williams told parents that the school would not rely on last-minute Saturday cramming as a substitute for weekly teaching. Extra lessons will support mathematics, English, the sciences and other high-entry subjects, but form teachers will still check ordinary homework. The programme is an intensification of the timetable, not a replacement for it.",
                "Heads of department submitted revision maps that name the topics most often failed in recent years. Mathematics will emphasise algebra, measurement and data handling. English will run timed writing under examination conditions. Science will protect practical time even when the calendar feels crowded. Business and technical subjects have their own coursework clocks, which the programme now displays on a single board outside the staff room.",
            ],
            bullets=[
                "Monday and Wednesday after-school sessions for mathematics and English",
                "Science practical catch-up on selected Thursdays",
                "SBA submission checkpoints with signatures from supervisors",
                "A December mock window before the Christmas break",
            ],
            quote="CSEC is not a surprise if the school refuses to treat it as one. The surprise is only for the student who waits until April to begin. — Mr. Andre Williams, Vice Principal — Academic Affairs",
            more=[
                "Students received a booklet that looks unromantic: dates, rooms, what to bring. That is the point. Anxiety loves rumour. A published plan reduces the market for rumour. The guidance department added a page on sleep, phones and the difference between studying and staring at a highlighted page.",
                "Not every candidate is in the same place. Some arrived from Grade 10 with completed coursework and a habit of independent study. Others are still negotiating with a subject they barely passed in mock tests last year. The programme therefore includes small-group sessions, not only hall lectures. Mr. Dwayne Thomas will run a mathematics clinic that does not allow a student to hide in the back row.",
                "Parents were asked to protect the extra-lesson hours from errands and from the kind of household work that can wait. The school knows that some families cannot. Form teachers will record attendance and call home when a pattern appears, not after a child has already disappeared from the list. Christiana High School cannot sit the examination for anyone. It can refuse to be surprised by absence.",
                "The library extended evening hours twice a week, a small change that matters for students who share a crowded house. Mrs. Yvonne McKenzie posted a sign: quiet is a resource. Past papers are another. New boxes of resources arrived this term, and Grade 11 has first claim on the ones that match current syllabuses.",
                "Teachers spoke plainly about malpractice. Phones in an examination room, copied SBAs and the borrowing of another student’s practical results will be treated as the serious offences they are. The school would rather lose a predicted grade than send a dishonest one into the world with its crest attached.",
                "By the end of the first fortnight, the programme had the feel of a new season. Some students complained about the loss of free afternoons. Prefects reminded them that May is not a rumour. Christiana High School’s CSEC story will be written in these ordinary extra hours, in marked scripts returned quickly, and in the stubborn decision to begin in October rather than in panic.",
                "Department meetings now end with a single question: which Grade 11 students are invisible? The names that surface are not always the loudest or the weakest. Sometimes they are the quietly average children who could earn a Grade II if someone noticed the missing coursework. The preparation programme is, at bottom, a machine for noticing.",
                "Christiana High School has no interest in pretending that every candidate will collect a hatful of Grade Is. It does intend that every candidate will have been taught, checked, fed past papers and told the truth about their standing while there is still time to change it. That is what a preparation programme is for.",
            ],
        ),
    },
    {
        "slug": "christiana-high-hosts-parent-teacher-consultation",
        "title": "Christiana High Hosts Successful Parent-Teacher Consultation",
        "excerpt": "Parents filled the hall and classrooms for a consultation evening that focused on attendance, coursework and how families can support learning at home.",
        "category": "Community",
        "author": "PTA Desk",
        "date": "2025-11-20",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 30,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School hosted a parent-teacher consultation that ran past the advertised closing time, which the staff chose to treat as a compliment rather than a failure of the clock. Classrooms stayed open. The hall served as overflow. The canteen sold the last boxed drinks before 8 p.m.",
            paras=[
                "Form teachers began with attendance and punctuality before moving to subject comments. Several parents said they had not realised how quickly a pattern of lateness becomes a pattern of missed instruction. Vice Principal Simone Brown asked families to treat the first bell as a community agreement, not a personal preference.",
                "Academic conversations clustered around Grade 10 and 11 coursework. Parents of younger students asked about reading at home and about phones. The guidance office kept a side table for families who needed a quieter conversation than a classroom queue allowed.",
            ],
            bullets=[
                "Bring the most recent report and any letters from subject teachers",
                "Ask what still needs to be submitted, not only what the grade is",
                "Leave a working phone number if the one on file has changed",
            ],
            quote="If you wait until mock examinations to meet the teacher, you have waited until the story is almost written. — Mrs. Simone Brown",
            closing=[
                "The PTA collected suggestions about lighting in the upper parking area and about earlier letters for extra-lesson schedules. Those notes went to the office the next morning. Consultation evenings work when they produce both information and a slightly thicker trust. Christiana High School will host another before Easter, and it will again ask parents to come while there is still time to change a child’s year.",
            ],
        ),
    },
    {
        "slug": "students-shine-inter-school-athletics-meet",
        "title": "Students Shine at Inter-School Athletics Meet",
        "excerpt": "Christiana High athletes returned from an inter-school meet with medals in sprints, relays and field events, and with a longer list of personal bests.",
        "category": "Sports",
        "author": "Sports Department",
        "date": "2026-02-16",
        "featured": True,
        "home": True,
        "priority": 3,
        "image": 4,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School’s track and field athletes put the hills into their running last weekend, returning from an inter-school meet with medals, personal bests and a bus that sang the whole way home. The meet gathered schools from across Manchester and neighbouring parishes. Our students arrived early, warmed up on a borrowed stretch of grass, and treated the call room with a seriousness that pleased the coaches.",
            heading="Results and character",
            paras=[
                "Sprints, relays and selected field events produced the headline performances, but the staff were equally glad of the athletes who finished off the podium without folding. A Grade 9 jumper improved her personal best by a margin that will not make the newspaper and will still change how she trains on Tuesday.",
                "Mr. Omar Bennett thanked parents who provided water and transport, and he named the prefects who managed kit bags without drama. Sports, he said in a later assembly, is one of the ways a school practises national pride without waiting for a public holiday.",
            ],
            quote="Run through the line. Then thank the people who waited in the sun. — Coach’s note on the whiteboard",
            closing=[
                "Training resumes this week with an eye on sports day and on the next inter-school fixture. Students who wish to trial late should see the PE office; enthusiasm after a medal photograph is welcome, but it will be tested at 6:30 a.m. Christiana High School will keep sending teams that look like a school: mixed ability, mixed houses, one crest.",
            ],
        ),
    },
    {
        "slug": "science-department-launches-environmental-awareness-project",
        "title": "Science Department Launches Environmental Awareness Project",
        "excerpt": "Christiana High’s science department has launched an environmental project that links laboratory work, the school garden and community clean-up.",
        "category": "Academic",
        "author": "Science Department",
        "date": "2025-10-28",
        "featured": False,
        "home": True,
        "priority": 0,
        "image": 17,
        "length": "long",
        "content": rich_html(
            lead="The science department at Christiana High School has launched an environmental awareness project that refuses to treat ‘the environment’ as a poster of a whale. Students will measure, plant, sort waste, and explain their findings to younger classes. The work sits inside biology, chemistry, geography and the 4-H club, which means it will appear in books as well as on the school Instagram that does not yet exist.",
            heading="Learning by measuring",
            paras=[
                "Mrs. Alicia Thompson told assembly that the first task is observation. Grade 9 classes will map litter hotspots on campus. Grade 10 will test soil from the garden beds. Grade 11 will design simple experiments around water use in the laboratories. The point is not a single clean-up day that looks good in a photograph. The point is a habit of asking what the data says.",
                "Mr. Christopher Haynes will link the project to drainage, slope and the particular weather of upper Manchester. Students who walk to school already know when the road floods. Geography will give them language for that knowledge. Science will give them methods.",
            ],
            bullets=[
                "Weekly garden duties assigned by house",
                "A waste-audit in the canteen over four school days",
                "A science-fair strand reserved for environmental investigations",
                "A short briefing for Grade 7 on laboratory safety and campus care",
            ],
            quote="If you can measure it, you can stop making speeches about it and start changing it. — Mrs. Alicia Thompson",
            heading2="Beyond the fence",
            more=[
                "The project includes a community element: a planned clean-up with a neighbouring basic school and a conversation with market vendors about packaging waste. Those activities will be supervised, time-tabled and risk-assessed. They are not an excuse to miss mathematics.",
                "Parents have been asked not to send drinks in the most fragile plastics when a reusable bottle would do. The school is not running a campaign against the shop down the road. It is running a campaign against thoughtlessness. Students who litter after an environmental assembly will hear about it twice: once from a teacher and once from a prefect who is tired of picking up the same bottles.",
                "Mr. Rohan Barrett, the laboratory technician, has already begun labelling extra containers for the soil work. His inventory list is the unglamorous backbone of every ‘exciting’ science initiative. The department knows that a project dies when the chemicals run out and nobody reorders. This one has a budget line, which is a kind of love letter from the bursar.",
                "Christiana High School sits in a landscape that still grows food, catches rain and sends young people into climate-changed adulthood. An environmental project is therefore not a fashion. It is vocational. Some of these students will farm. Some will nurse through hotter years. Some will write policy. All of them will live with water, waste and weather. The science department intends that they live as people who paid attention.",
                "Later this term the hall will host a small exhibition of graphs, photographs and plant samples. Visitors should not expect perfection. They should expect evidence. That, Mrs. Thompson said, is what a school owes a community that still drinks from tanks and still plants yam when the rain is kind.",
                "Teachers in other departments have been invited to join without turning the project into a slogan on every worksheet. English may take a reflective paragraph. Social studies may take a short debate on local government and garbage collection. The science department will keep the spine of the work: hypothesis, method, result, honesty about error.",
                "If the project succeeds, it will look boring from a distance: wet shoes, clipboards, a compost heap that is not photogenic. That is how environmental education should look in a working high school. Christiana High School is prepared to be boring in that useful way.",
                "Later in the term, Grade 8 will join a shortened version of the waste audit so that environmental work is not reserved for examination classes. Younger students already know where the litter gathers after break. Giving them a clipboard turns a complaint into a method. Prefects will help, not as police, but as people who are tired of picking up the same bottles.",
                "The science department has asked other staff not to cancel the project when the calendar gets crowded. CSEC practicals will still come first in Grade 11 weeks, and the garden will still need water on those weeks. A school that only loves the environment on a poster day has not understood its own syllabus. Christiana High School would like this project to become as ordinary as a register: noticed when it is missing, unremarkable when it is done.",
            ],
        ),
    },
    {
        "slug": "mathematics-department-after-school-support",
        "title": "Mathematics Department Introduces After-School Support Programme",
        "excerpt": "Mr. Dwayne Thomas and the mathematics team have opened after-school clinics for students who need more time with algebra, measurement and past papers.",
        "category": "Academic",
        "author": "Mathematics Department",
        "date": "2025-11-05",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 39,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School’s mathematics department has introduced an after-school support programme for students who need more than the forty-minute lesson. The clinics are quiet, mixed-grade when necessary, and allergic to the sentence ‘I just can’t do maths’.",
            paras=[
                "Mr. Dwayne Thomas said the programme is not a detention and not a gifted club. It is extra time with worked examples, whiteboards and the requirement that a student attempt the next question before declaring defeat. Mr. Lamar Dixon will take the lower-school groups so that Grade 7 errors do not harden into Grade 11 panic.",
                "Attendance is tracked. Parents received a letter listing days and rooms. Students who come for the first twenty minutes and then drift toward the tuck shop will be sent home with a note that tells the truth about it.",
            ],
            quote="Mathematics rewards the person who stays. Stay. — Notice on the clinic door",
            closing=[
                "The department will review the programme at the end of term against a simple measure: are more students completing homework, and are fewer arriving at mock examinations with blank algebra pages? Christiana High School would rather adjust a timetable now than write a sad report in June.",
            ],
        ),
    },
    {
        "slug": "christiana-high-celebrates-jamaica-day",
        "title": "Christiana High Celebrates Jamaica Day",
        "excerpt": "Colour, food, folk songs and classroom exhibitions filled the campus as Christiana High School marked Jamaica Day.",
        "category": "Student Life",
        "author": "Student Life Desk",
        "date": "2026-05-23",
        "featured": False,
        "home": True,
        "priority": 0,
        "image": 11,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School celebrated Jamaica Day with the seriousness of people who know that culture is not a costume and the joy of people who still like a costume. Students arrived in madras, bandana and the occasional inventive use of a tablecloth. The assembly ground smelled of food before first period had ended.",
            heading="Classrooms and courtyard",
            paras=[
                "Heritage exhibitions spilled from the hall into the corridor: maps, proverbs, photographs of market day, and a Spanish-language stall run by Mrs. Patrice Gordon’s classes. Mr. Kemar Grant coordinated the social studies displays and refused to let a printed flag stand in for a researched caption.",
                "The choir sang. A Grade 8 group performed a short folk piece that had been rehearsed more times than anyone wished to admit. Teachers who claimed they could not dance were photographed dancing, which is the point of a school holiday that is still a school day.",
            ],
            bullets=[
                "Morning assembly with patriotic songs and a short history reflection",
                "Department exhibitions on food, language, sport and independent Jamaica",
                "A quiet collection for a community project after the celebrations",
            ],
            quote="Wear the colour. Then learn the story that made the colour mean something. — Ms. Renee Walters, History",
            closing=[
                "Jamaica Day at Christiana High School is not a break from education. It is education in a louder shirt. Students went home tired, slightly sunburnt, and — if the teachers succeeded — a little more able to explain why the motto on the crest is a national sentence as well as a school one.",
            ],
        ),
    },
    {
        "slug": "student-leaders-leadership-workshop",
        "title": "Student Leaders Participate in Leadership Workshop",
        "excerpt": "Prefects, house captains and club presidents spent a Saturday morning learning how to run a meeting, give a warning and represent the school.",
        "category": "Student Life",
        "author": "Student Affairs",
        "date": "2025-09-27",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 42,
        "length": "short",
        "content": rich_html(
            lead="Student leaders at Christiana High School spent a Saturday morning in a leadership workshop that mixed role-play, plain talk and a long list of situations that never appear in the prefect handbook.",
            paras=[
                "Mrs. Simone Brown and Mrs. Alexandra-Marie Elizabeth Thompson-Williams led sessions on how to give a warning without performing power, how to chair a club meeting, and how to report a serious matter instead of gossiping about it. Prefects practised assembly announcements until the mumbling stopped.",
                "Participants left with a one-page code: be early, be fair, write things down, and remember that a badge is not a personality. The school will repeat a shorter version of the workshop for new house captains after sports day trials.",
            ],
        ),
    },
    {
        "slug": "school-football-team-advances-next-round",
        "title": "School Football Team Advances to Next Round",
        "excerpt": "Christiana High School’s footballers advanced to the next round of their inter-school competition after a disciplined away performance.",
        "category": "Sports",
        "author": "Sports Department",
        "date": "2026-01-22",
        "featured": False,
        "home": True,
        "priority": 0,
        "image": 3,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School’s football team has advanced to the next round of competition after an away fixture that was short on luxury and long on running. The players travelled early, warmed up on a patchy surface, and kept their shape after conceding a nervous first chance.",
            paras=[
                "Mr. Omar Bennett praised the midfield’s work rate and the quiet leadership of the captain, who spent more time organising the back line than celebrating. Substitutes stayed ready. The bench, he said, is part of the team even when it does not touch the ball.",
                "Supporters from Christiana made the trip in a mix of private cars and a hired bus that returned later than planned and still found parents waiting at the gate. The school thanked them in Monday’s assembly and then sent the players back to training — medals, if they come, will not replace Tuesday’s fitness work.",
            ],
            quote="Advance like people who still have homework. — Notice in the changing area",
            closing=[
                "The next round will demand a higher standard. Students were reminded that footballers remain students: attendance, uniform and classroom conduct are part of selection. Christiana High School will not field a team that treats the crest as a costume for Saturdays only.",
            ],
        ),
    },
    {
        "slug": "christiana-high-hosts-career-day",
        "title": "Christiana High Hosts Career Day",
        "excerpt": "Professionals from health, agriculture, public service, business and the trades spent a day on campus speaking with students about real work.",
        "category": "Community",
        "author": "Guidance Department",
        "date": "2026-03-12",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 16,
        "length": "long",
        "content": rich_html(
            lead="Christiana High School hosted Career Day in a hall that smelled of furniture polish and nerves. Students rotated through stations staffed by nurses, teachers, police officers, farmers with accounts, IT technicians, small-business owners and two alumni who had come from Kingston without making a speech about sacrifice. The day was designed by the guidance department to answer a simple question: what does work look like when the uniform comes off?",
            heading="Stations and conversations",
            paras=[
                "Ms. Keisha Morgan told Grade 9 that Career Day is not a promise of a job. It is a map of possibilities and of the subjects that still have to be passed. Sixth-formers had longer conversations about university, HEART/NSTA Trust programmes and the unromantic matter of how to pay for either.",
                "Teachers released classes on a staggered timetable so the hall never became a crush. Prefects managed queues. A few students tried to hide in the bathroom. They were collected, without theatre, and returned to a station about the trades — a reminder that avoidance is also a career plan, just a poor one.",
            ],
            bullets=[
                "Health and allied professions",
                "Agriculture, agri-business and environmental work",
                "Education, public service and the security forces",
                "Information technology and skilled trades",
                "Entrepreneurship and retail in a market town",
            ],
            quote="Pick a direction, then pick the subjects that will still be standing when the excitement fades. — Ms. Keisha Morgan",
            more=[
                "Several speakers had attended Christiana High School or nearby institutions. Their presence mattered more than any imported keynote. A young nurse described shift work. A mechanic described the difference between liking cars and invoicing honestly. An accounts clerk described boredom as a skill one can learn to manage. Students laughed, then wrote things down.",
                "Parents who could leave work dropped in after lunch. Some stood at the back and listened to the same talk their child had heard, which is one of the hidden gifts of Career Day: a family gets a shared vocabulary. The bursar’s table answered questions about scholarships without pretending that scholarships are plentiful.",
                "The technology club ran a small demonstration of document creation and file organisation that looked too basic to be a career and was, in fact, the start of several. Mr. Ricardo Johnson told students that nobody hires a person who cannot name a file. It was the least glamorous sentence of the day and possibly the most useful.",
                "By dismissal the hall was scattered with brochures and the particular tiredness that follows hope. Form teachers collected reflection sheets. Guidance will follow up with students whose sheets were blank or whose ambitions had no relationship to their attendance. Career Day is a beginning. The timetable is the rest of the argument.",
                "Christiana High School will host another careers conversation in the first term next year, smaller and aimed at Grade 11 subject choices. The staff already have a list of speakers who promised to return. The school’s task is to keep the gate open to the working world without turning education into a job fair with hymns.",
                "In her closing remarks, Dr. Campbell reminded students that dignity is not reserved for the professions with long titles. A farmer who keeps records, a mason who finishes a wall, a teacher who marks books — all of them are answers to the question of what a life can be. Career Day at Christiana High School tried to make that range visible in one crowded hall.",
                "The day ended, as school days do, with a bell and a bus. What remains is the quieter work of subject choices, extra lessons and the courage to ask a teacher, while there is still time, whether a dream and a grade book can be made to meet.",
                "Several Grade 9 students lingered at the trades table after the hall had begun to empty, asking about HEART programmes and whether a person can still sit CSEC while learning a skill. That is the conversation Career Day is for. The glamour of a visiting doctor matters; the honesty of a technician who describes a Tuesday matters more. Guidance will keep the speaker list and invite the same people back before subject-choice week.",
                "Christiana High School sits in a town that already contains most of the jobs on the posters, even if students sometimes look past them toward Kingston. Career Day tried to honour both instincts: stay and build, or leave prepared. Either path still requires English, mathematics, punctuality and the ability to look an adult in the eye. Those requirements were named without apology.",
            ],
        ),
    },
    {
        "slug": "sixth-form-university-preparation-seminar",
        "title": "Sixth Form Students Attend University Preparation Seminar",
        "excerpt": "Lower and upper sixth students spent an afternoon on applications, personal statements, financing and the difference between wanting university and being ready for it.",
        "category": "Academic",
        "author": "Sixth Form Office",
        "date": "2026-01-30",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 20,
        "length": "medium",
        "content": rich_html(
            lead="Sixth-form students at Christiana High School attended a university preparation seminar that treated applications as work rather than as magic. The session covered deadlines, personal statements, financing, and the gap between a CAPE timetable and the independence of a campus.",
            paras=[
                "Speakers included an admissions officer who attended remotely and two alumni who spoke in person about the first semester’s loneliness and the library’s lights. Ms. Keisha Morgan facilitated questions that students are often too proud to ask in a mixed group: What if my grades are uneven? What if my family cannot pay?",
                "Teachers of CAPE subjects stayed for the last hour to connect unit choices with intended programmes. The message was consistent. University is a continuation of habits already visible in sixth form: reading, showing up, submitting work that is yours.",
            ],
            quote="Do not write a personal statement about leadership if you will not run a club meeting this term. — Alumni speaker",
            closing=[
                "Students left with a checklist and a date for a follow-up workshop on financing. Christiana High School cannot place every sixth-former in a lecture hall. It can refuse to let them arrive at August unprepared.",
            ],
        ),
    },
    {
        "slug": "debate-team-regional-competition",
        "title": "Debate Team Represents School at Regional Competition",
        "excerpt": "The Christiana High debate team represented the school at a regional competition with motions on education, environment and youth employment.",
        "category": "Achievements",
        "author": "English Department",
        "date": "2026-02-27",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 42,
        "length": "short",
        "content": rich_html(
            lead="Christiana High School’s debate team represented the campus at a regional competition, speaking on education policy, environmental responsibility and youth employment with a composure that survived even the hostile motions.",
            paras=[
                "Mrs. Danielle Simpson, who coaches the team, said the point of travel is not only the trophy table. It is the discovery that a student from Christiana can take a definition, a set of examples and a rebuttal into a hall of strangers and be heard. The team did not win every round. They won the right to be invited back.",
                "English classes watched a short recording in the following week. Several Grade 9 students asked how to join. Practice remains on Thursdays. Bring a pen, not a performance.",
            ],
        ),
    },
    {
        "slug": "school-library-new-learning-resources",
        "title": "School Library Receives New Learning Resources",
        "excerpt": "New books, past-paper collections and reference materials have arrived in the Christiana High School library.",
        "category": "Announcements",
        "author": "Library",
        "date": "2025-12-04",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 8,
        "length": "short",
        "content": rich_html(
            lead="The Christiana High School library has received a new shipment of learning resources, including subject texts, Caribbean literature, past-paper collections and reference materials that Mrs. Yvonne McKenzie has already begun to catalogue.",
            paras=[
                "Grade 11 has priority borrowing on the examination-related titles until the mock window closes. Other students may use the collection in the library during opening hours. Damaged books will be charged to the borrower, a sentence the librarian has laminated.",
                "The school thanked donors, including alumni who sent parcels without asking for a plaque. A quiet library with current books is still one of the cheapest ways to take a child seriously.",
            ],
        ),
    },
    {
        "slug": "technology-club-digital-skills-initiative",
        "title": "Technology Club Launches Digital Skills Initiative",
        "excerpt": "The technology club has launched a digital skills initiative to help students create documents, manage files and work with basic data tools.",
        "category": "Academic",
        "author": "Information Technology",
        "date": "2026-01-16",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 2,
        "length": "medium",
        "content": rich_html(
            lead="Christiana High School’s technology club has launched a digital skills initiative aimed at students who can use a phone for everything except the document their teacher actually asked for. Sessions will cover file management, word processing, simple spreadsheets and the ethics of copying work from the internet.",
            paras=[
                "Ms. Bianca Clarke and Mr. Ricardo Johnson will run after-school labs in small groups so that no one can hide behind a crashed browser. Mr. Nicholas Grant has promised that the machines will be working enough for Monday, which is now an official technical standard.",
                "The initiative is open across grades, with Grade 11 SBA needs taking precedence near deadlines. Students must sign an acceptable-use agreement that forbids the usual creative uses of school computers.",
            ],
            quote="If your file is called Document1, you have not started. — Lab notice",
            closing=[
                "A public showcase later in the year will display student-made posters, simple data charts and a short film about campus life. Until then, the work is unglamorous and necessary. Christiana High School would like its graduates to arrive in offices and lecture rooms able to attach a file that opens.",
            ],
        ),
    },
    {
        "slug": "students-community-outreach-project",
        "title": "Students Participate in Community Outreach Project",
        "excerpt": "Christiana High students spent a service morning with a neighbouring basic school, reading, packing supplies and cleaning an outdoor play area.",
        "category": "Community",
        "author": "Student Affairs",
        "date": "2026-04-10",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 18,
        "length": "medium",
        "content": rich_html(
            lead="Students from Christiana High School took their uniform into the wider community for an outreach morning that combined reading with younger children, a tidy-up of an outdoor play area, and the packing of school-supply kits.",
            paras=[
                "The Interact club and selected Grade 10 classes joined under staff supervision. Prefects discovered that leading a high-school corridor is easier than sitting still with a six-year-old who wants the same book twice. That, teachers said, is also education.",
                "Parents donated pencils, copybooks and a surprising number of erasers. The school nurse sent a small first-aid refresher with the team. Nobody was allowed to treat the morning as a day off from mathematics; classes resumed after lunch.",
            ],
            closing=[
                "Outreach will return in a different form next term. Christiana High School’s point is not a single photograph of students holding brooms. It is the habit of noticing that the town’s children are ours even when they wear a different crest, or none.",
            ],
        ),
    },
    {
        "slug": "christiana-high-recognises-outstanding-academic-achievement",
        "title": "Christiana High School Students Demonstrate Excellence in Academics, Leadership, Innovation and Community Service During Annual Achievement Celebration",
        "excerpt": "The annual achievement celebration honoured scholars, student leaders, innovators and young people whose service quietly holds the campus together.",
        "category": "Achievements",
        "author": "Principal's Office",
        "date": "2026-07-03",
        "featured": True,
        "home": True,
        "priority": 1,
        "image": 10,
        "length": "long",
        "content": rich_html(
            lead="Christiana High School packed the hall for its annual achievement celebration, a long afternoon of names, certificates, cautious applause and the particular pride that moves through a rural high school when a child’s work is read out in front of the people who paid the bus fare. The programme honoured academic excellence, student leadership, innovation in clubs and classrooms, and community service that rarely makes a fuss.",
            heading="More than a prize list",
            paras=[
                "Dr. Marsha Campbell told the gathering that a prize-giving which only crowns the already obvious has failed half the roll. The school therefore named improvement as well as distinction: the student who moved a mathematics grade, the class with the strongest coursework completion, the house that kept the campus clean without being asked every week.",
                "Heads of department presented subject awards with the mix of formality and teasing that keeps a Jamaican staff table human. Parents fanned themselves. A baby cried at the exact moment a Grade 11 scholar reached the microphone, which the hall chose to find funny rather than ruinous.",
            ],
            bullets=[
                "Academic awards across CSEC and lower-school subjects",
                "Leadership citations for prefects, house captains and club presidents",
                "Innovation mentions for science, technology and the arts",
                "Service awards for outreach, peer support and campus care",
            ],
            quote="Excellence is a habit you can photograph today, but it was built on ordinary Tuesdays when nobody was clapping. — Dr. Marsha Campbell",
            heading2="Leadership, innovation and service",
            more=[
                "Student leaders were recognised not for the badge but for the minutes of meetings that actually happened, for the younger students who were corrected without being shamed, and for the assembly announcements that could be heard at the back. Mrs. Thompson-Williams read a short citation that made even the restless Grade 8 row sit up.",
                "Innovation awards went to a science group whose environmental measurements were honest about error, to a technology-club team that taught file management to Grade 7, and to a visual-arts student whose exhibition made the office corridor briefly beautiful. The school is careful with the word innovation. It does not mean a gadget. It means a better way of doing a necessary thing.",
                "Community service citations named students who packed kits, read with basic-school children, and stayed to sweep the hall when the exciting part of an event was over. Service, the Principal said, is how a school practises the motto when the hymn is finished.",
                "The longest part of the afternoon was also the most important: the reading of names. Every name is a bus ride, a lunch, a form teacher’s patience, a parent’s evening. Christiana High School does not have the luxury of treating a certificate as a small piece of paper. In a town that still measures success by who ‘got through’, the hall is a public accounting.",
                "Alumni in the audience were invited to stand. Some had left ten years ago and still knew the house song. Their presence told present students that achievement is not a single night. It is a reputation you carry into workplaces that have never heard of your form teacher and will still judge you by the habits she taught.",
                "Not every deserving student was on the stage. Staff know the quiet child whose improvement is real and whose family could not attend. Form teachers were asked to repeat congratulations in class the next day, where the lighting is worse and the meaning is sometimes better. A school that only celebrates in the hall will forget the corridor.",
                "The programme closed with the school song, a photograph that took too long, and the ordinary miracle of chairs stacked by students who had just been praised and were still willing to work. That combination — honour and duty in the same hour — is what Christiana High School is trying to grow.",
                "Looking toward the new academic year, the administration will keep the achievement assembly as a fixture and keep widening the categories so that a footballer, a librarian’s helper and a chemistry scholar can all hear their names in the same room. Excellence, on this campus, is a crowded word. It needs a crowded stage.",
                "Parents who left with certificates in plastic sleeves were asked to put them on the wall and then to ask about the next test. Celebration without a next target is just a party. Christiana High School likes a party. It likes a Tuesday morning more.",
                "The lights in the hall clicked off. The crest on the curtain looked briefly like a secret. Then the watchman locked the door, and the school’s achievement became, again, a matter of lesson plans, marked books and the students who will try to deserve next year’s list. That is the right ending for a long afternoon of applause.",
                "After the ceremony, department heads gathered leftover certificates for students whose families could not attend. Those envelopes will travel in schoolbags tomorrow, slightly bent, still meaning the same thing. A prize that arrives a day late is still a public record that somebody noticed the work.",
                "The academic awards spanned mathematics, English, the sciences, business, information technology, history, geography, the arts and technical studies. No department was allowed to treat the afternoon as optional. A school that only crowns footballers or only crowns scholars has already chosen a smaller future than Christiana High School can afford.",
                "Innovation citations included a data log from the garden project, a set of files from the digital skills initiative, and a drama piece that used Jamaican speech without turning it into a joke. Service citations included packing kits, walking Grade 7 students to the right classroom in September, and staying to stack chairs. Leadership citations named prefects who wrote minutes and house captains who settled a quarrel before it reached the office.",
                "Community partners who donated trophies were thanked without being allowed to turn the hall into an advertisement. Dr. Campbell’s closing charge returned to the motto: our best Jamaica hope is not a caption under a photograph. It is the next homework, the next apology, the next extra lesson, and the next kind word in a corridor that still smells of floor polish and nerves.",
            ],
        ),
    },
    {
        "slug": "guidance-mental-health-awareness-session",
        "title": "Guidance Department Hosts Mental Health Awareness Session",
        "excerpt": "Students and staff joined a guidance session on stress, sleep, asking for help, and the difference between ordinary pressure and a crisis.",
        "category": "Student Life",
        "author": "Guidance Department",
        "date": "2026-02-06",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 48,
        "length": "medium",
        "content": rich_html(
            lead="The guidance department at Christiana High School hosted a mental-health awareness session that tried to be useful rather than fashionable. Students heard about sleep, exam stress, grief, and how to ask for help without performing a crisis they do not have — or hiding one they do.",
            heading="What students were asked to remember",
            paras=[
                "Ms. Keisha Morgan told the hall that toughness is not the same as silence. A student who cannot sleep, who has stopped eating, or who is being hurt is not ‘attention-seeking’ by walking to the guidance office. Staff were present, including form teachers who had been briefed on how to listen without turning a confidence into corridor news.",
                "The session used short scenarios rather than long lectures. Peer counsellors practised phrases that open a door and phrases that close one. Nurse Patricia Henry added a practical note on headaches, hydration and when a pain is not ‘just stress’.",
            ],
            bullets=[
                "Tell a trusted adult early",
                "Do not diagnose your friends; do walk with them to the office",
                "Phones at midnight are not a sleep strategy",
                "Confidentiality has limits when someone is in danger",
            ],
            quote="You are allowed to need help and still be a strong student. Those are not opposites. — Ms. Keisha Morgan",
            closing=[
                "Follow-up small groups will run for Grade 11 in the approach to mocks. Parents who wish to talk may request an appointment through the office. Christiana High School cannot solve every private sorrow. It can refuse to pretend that young people in the hills do not have them.",
            ],
        ),
    },
    {
        "slug": "performing-arts-annual-showcase",
        "title": "Performing Arts Students Prepare for Annual Showcase",
        "excerpt": "Drama, choir and dance students are in late rehearsals for the Christiana High annual showcase, with tickets due to go on sale at the office.",
        "category": "Student Life",
        "author": "Performing Arts",
        "date": "2026-04-24",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 13,
        "length": "medium",
        "content": rich_html(
            lead="Performing arts students at Christiana High School have entered the late-rehearsal stretch of the annual showcase, that period when costumes go missing, a soloist gets a cold, and Mr. Jermaine Powell’s voice carries farther than the hall’s speakers.",
            paras=[
                "The programme will mix drama, choral work and dance, including original pieces written in English class and a short folk item that survived Jamaica Day. Visual arts students are painting flats that will hide a multitude of sins and one very solid piece of carpentry from the technical department.",
                "Tickets will be sold at the office. Prefects will usher. Parents are asked to arrive on time; the show will start without the traditional thirty minutes of Jamaican extra time if Mr. Powell has his way, which he usually does by the second night.",
            ],
            quote="Know your line. Then know the person next to you. — Rehearsal note",
            closing=[
                "Students who are not on stage are still needed for lighting, programmes and the unglamorous work of sweeping afterwards. The showcase is a school event, not a private concert. Christiana High School expects the crest to look as good in the dark of the hall as it does on Sports Day.",
            ],
        ),
    },
    {
        "slug": "school-garden-sustainable-agriculture",
        "title": "School Garden Project Promotes Sustainable Agriculture",
        "excerpt": "The Christiana High garden is feeding lessons in science, 4-H and a modest kitchen harvest that tastes like patience.",
        "category": "Community",
        "author": "4-H and Science",
        "date": "2026-03-28",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 17,
        "length": "short",
        "content": rich_html(
            lead="The school garden at Christiana High School is once again a classroom with dirt under its fingernails. Students in science and 4-H have planted, mulched and kept a harvest log that treats a tomato as data as well as dinner.",
            paras=[
                "Mrs. Alicia Thompson and club leaders use the beds to talk about water, soil and the difference between a project that lasts a term and a farm that has to last a life. A small share of produce went to the staff room; a smaller share went home with students who had done the weeding.",
                "Visitors are welcome to look, not to pick. The garden is fenced against goats, theft and the particular optimism of Grade 7. Sustainable agriculture, on this campus, begins with a hoe and a register of whose turn it is to water.",
            ],
        ),
    },
    {
        "slug": "christiana-high-end-of-term-activities",
        "title": "Christiana High Announces End-of-Term Activities",
        "excerpt": "The school has published end-of-term activities including assemblies, club showcases, a quiet study day and the last date for returning library books.",
        "category": "Announcements",
        "author": "School Office",
        "date": "2026-07-10",
        "featured": False,
        "home": False,
        "priority": 0,
        "image": 15,
        "length": "short",
        "content": rich_html(
            lead="Christiana High School has announced end-of-term activities for students and staff, a mix of celebration, administration and the last chance to return a library book without a fine.",
            paras=[
                "The calendar includes a final assembly, club showcases, a quiet study day for examination classes still in session, and a staff marking day when students should not expect the office to invent extra report comments on the spot. Parents should collect reports on the published date.",
                "Students are asked to leave classrooms tidy, to settle canteen debts, and to remember that holidays are not an excuse to forget the uniform rules on the first morning back. The gate will still be there in September. So will the school.",
            ],
        ),
    },
]


assert len(NEWS) == 20


def event_desc(paras: list[str], extra: list[str] | None = None) -> str:
    return paragraphs_to_html(paras + (extra or []))


EVENTS = [
    {
        "slug": "new-student-orientation",
        "title": "New Student Orientation",
        "date": "2026-09-04",
        "start": "8:30 a.m.", "end": "12:30 p.m.",
        "venue": "School hall and campus tour",
        "category": "Student activities",
        "image": 22,
        "home": True,
        "description": event_desc([
            "New students and their parents are invited to Christiana High School for an orientation that covers the timetable, the code of conduct, house assignments and a walking tour of the campus. Prefects will lead groups; form teachers will collect contact numbers; the bursar’s office will answer fee questions in a side room.",
            "Students should wear the school uniform. Parents should bring any outstanding documents. The morning will end with a short assembly so that Grade 7 hears the school song from inside the hall rather than from a video.",
        ]),
    },
    {
        "slug": "parent-teacher-consultation",
        "title": "Parent-Teacher Consultation",
        "date": "2026-10-15",
        "start": "2:00 p.m.", "end": "6:30 p.m.",
        "venue": "Classrooms and school hall",
        "category": "PTA",
        "image": 30,
        "home": True,
        "description": event_desc([
            "Parents are invited to meet form and subject teachers at Christiana High School. Please bring the most recent report. Queues move faster when families arrive with specific questions about attendance, coursework and the next target rather than a general hope that everything is fine.",
            "The guidance office will be open for private conversations. The canteen will sell light refreshments. Teachers will leave at the published time; late arrivals may not be seen.",
        ]),
    },
    {
        "slug": "csec-mathematics-workshop",
        "title": "CSEC Mathematics Workshop",
        "date": "2026-10-15",
        "start": "9:00 a.m.", "end": "12:00 p.m.",
        "venue": "Mathematics block",
        "category": "Academic",
        "image": 39,
        "home": False,
        "description": event_desc([
            "Grade 11 candidates are expected at a CSEC mathematics workshop focused on algebra, measurement and data handling. Bring past papers, a calculator with working batteries, and the humility to attempt the next question.",
            "Mr. Dwayne Thomas and Mr. Lamar Dixon will run rotating clinics. This workshop shares a date with parent-teacher consultation so that families who come for one may hear about the other.",
        ]),
    },
    {
        "slug": "annual-sports-day",
        "title": "Annual Sports Day",
        "date": "2026-02-20",
        "start": "8:30 a.m.", "end": "4:00 p.m.",
        "venue": "School field",
        "category": "Sports",
        "image": 45,
        "home": False,
        "featured": True,
        "description": rich_html(
            lead="Sports Day at Christiana High School is one of the great gatherings of the year: houses in colour, alumni on the banking, PTA stalls, and a field that has to survive both athletes and the crowd that loves them. The programme includes track events, selected field events, marching, and the unofficial competitions in shade, ice and commentary.",
            paras=[
                "Students should arrive in house wear as published. Athletes must check in with Mr. Omar Bennett before the first event. Parents are welcome; vehicles should follow the marshals, who have suffered enough.",
                "The day is a holiday from ordinary lessons and not a holiday from courtesy. Litter, rude heckling and early departures that leave a house short of a relay team will be remembered at the next assembly.",
            ],
            more=[
                "Houses will march past after the opening ceremony. The Principal will declare the meeting open. From that moment the clerk of the course, the starters and the tired people with clipboards become the government of the field. Students who are not competing are still on duty: water, banners, encouragement that does not spill onto the track.",
                "Alumni often return with stories of a particular hundred metres or a javelin that frightened a cow. They are part of the spectacle. They are also asked not to coach from inside the area of competition. The school has enough officials.",
                "First aid will be stationed near the finish. Nurse Henry has asked that ‘running it off’ not be the first medical plan for a genuine injury. The canteen and PTA stalls will trade all day; students with dietary needs should plan ahead rather than discover the menu at 2 p.m.",
                "Points will be displayed on a board that will be wrong at least twice before it is right. Arguments about the board should go to the appointed official, not to a cousin in the crowd. Christiana High School would like Sports Day to end with a trophy, a clean field, and enough daylight to stack the chairs.",
                "In the days after the meeting, PE classes will return to ordinary fitness and the footballers will complain that they are stiff. That stiffness is a kind of archive. It means the school still has a body as well as a timetable. Visitors who have never seen a rural sports day are welcome; they should bring a hat.",
            ],
        ),
    },
    {
        "slug": "jamaica-day-celebration",
        "title": "Jamaica Day Celebration",
        "date": "2026-05-23",
        "start": "8:30 a.m.", "end": "2:00 p.m.",
        "venue": "Assembly ground and hall",
        "category": "Holidays",
        "image": 11,
        "home": False,
        "description": event_desc([
            "Christiana High School will mark Jamaica Day with assembly, exhibitions and cultural items. Students may wear published national colours. Teachers will still take a register.",
            "The social studies, history, languages and performing arts departments will mount displays. A short collection for a community project will be taken after the celebrations, because patriotism that never gives anything away is just a shirt.",
        ]),
    },
    {
        "slug": "career-day",
        "title": "Career Day",
        "date": "2026-11-06",
        "start": "9:00 a.m.", "end": "2:30 p.m.",
        "venue": "School hall",
        "category": "Student activities",
        "image": 16,
        "home": True,
        "description": rich_html(
            lead="Career Day brings working adults onto the Christiana High School campus to talk honestly about nursing, teaching, farming, accounts, information technology, the trades, the security forces and the small businesses that keep a market town alive. Students will rotate through stations. Sixth-formers will have a longer block for university and financing questions.",
            paras=[
                "Ms. Keisha Morgan asks students to bring a notebook and at least one question that is not ‘How much do you earn?’ Speakers have been invited because they can describe a Tuesday, not only a title.",
                "Parents who can attend after lunch are welcome. The hall will be warm. The conversations may be warmer. Uniform is required; curiosity is required more.",
            ],
            more=[
                "The timetable will stagger classes so that Grade 9 does not arrive at the same minute as Grade 13. Prefects will manage doors. Students who disappear toward the tuck shop will be returned to a station, possibly the least glamorous one available.",
                "Christiana High School does not promise that Career Day will settle a life. It promises a clearer map of the subjects, habits and costs that stand between a dream and a doorway. Alumni speakers are scheduled; additional volunteers may still contact the guidance office.",
                "A reflection sheet will be collected by form teachers the next morning. Blank sheets will attract a conversation. The school would like Career Day to echo into subject choices, extra lessons and the way a student talks at the dinner table, not only into a photograph of a guest at a microphone.",
                "Speakers were asked to describe a typical Tuesday rather than a highlight reel. Students will hear about shift work, invoices, muddy boots, passwords and the unglamorous months before a qualification starts to pay. That honesty is a gift. Christiana High School would rather send a thoughtful child into a modest job than a confused child into a fantasy.",
                "Refreshments for speakers will be served in the staff room. Students should not loiter there unless invited. The day’s success will be measured later, in the office, when a Grade 11 child changes a subject combination for a reason that sounds like information rather than panic. Parents who attend are asked to listen first and advise later, at home, where the timetable becomes a family document.",
            ],
        ),
    },
    {
        "slug": "parent-student-community-partnership-conference",
        "title": "Annual Parent, Student and Community Partnership Conference and Academic Development Workshop",
        "date": "2026-10-22",
        "start": "9:00 a.m.", "end": "3:00 p.m.",
        "venue": "School hall",
        "category": "PTA",
        "image": 43,
        "home": True,
        "description": rich_html(
            lead="Christiana High School will host its Annual Parent, Student and Community Partnership Conference and Academic Development Workshop, a long-title day with a practical aim: to put families, student leaders, teachers and community partners in one room long enough to talk about learning, not only about problems.",
            paras=[
                "The morning session will address attendance, CSEC preparation, and how homes and classrooms can stop working against each other. The afternoon will split into workshops on literacy at home, digital safety, extra lessons, and the role of churches, clinics and businesses in supporting students.",
                "Student leaders will present a short, unsentimental report on campus life. Community partners are invited to staff information tables without turning the hall into a trade show.",
            ],
            more=[
                "Dr. Campbell and the vice principals will remain for the full day. Department heads will join the academic workshop block. Childcare is not provided; the conference is aimed at adults and at sixth-form observers who have been selected by the student council.",
                "Lunch will be simple. Conversations will not be. Families who have never attended a PTA meeting are especially welcome. The school would rather hear a hard question in October than a hard regret in June.",
                "Notes from the workshops will be typed and posted on the notice board the following week. Promises that cannot be kept will not be made at the microphone. Christiana High School is using this conference as a working session, not as a performance of partnership.",
                "The academic development workshop will include a short briefing on CSEC timelines, literacy at home, and how to read a report without treating every comment as an insult or a prophecy. Student leaders will stay for that block so they can translate the language of the staff room into the language of the corridor. Community partners will be asked for specific help — a mentor hour, a tool, a scholarship — rather than for applause.",
                "Parking marshals will be on duty. Visitors should enter by the main gate. The long name on the letter is deliberate: this is not a short speech with a prayer at each end. It is a day’s work on the relationship that makes a high school possible. Families who have never attended a PTA meeting are especially welcome; the school would rather hear a hard question in October than a hard regret in June.",
            ],
        ),
    },
    {
        "slug": "sixth-form-orientation",
        "title": "Sixth Form Orientation",
        "date": "2026-09-18",
        "start": "9:00 a.m.", "end": "1:00 p.m.",
        "venue": "Sixth-form block",
        "category": "Academic",
        "image": 20,
        "home": False,
        "description": event_desc([
            "Incoming sixth-form students will meet tutors, collect subject information and hear about the standard of independence the school expects. Dress is uniform. Bring writing materials and any CAPE-related correspondence already received.",
            "Parents may attend the first hour. The rest of the morning is for students, including a library briefing and a frank talk about attendance in a programme that is still school, not university.",
        ]),
    },
    {
        "slug": "inter-house-football-competition",
        "title": "Inter-House Football Competition",
        "date": "2026-09-25",
        "start": "1:30 p.m.", "end": "5:00 p.m.",
        "venue": "School field",
        "category": "Sports",
        "image": 3,
        "home": True,
        "description": event_desc([
            "Houses will compete in a football afternoon that is friendlier than ISSA and still capable of producing a serious tackle. Players must have been attending PE. Spectators must stay off the field.",
            "Mr. Bennett will referee arguments about eligibility with a list, not with a vibe. Bring water. Leave the jewellery at home.",
        ]),
    },
    {
        "slug": "science-fair",
        "title": "Science Fair",
        "date": "2026-03-12",
        "start": "9:00 a.m.", "end": "2:00 p.m.",
        "venue": "School hall and laboratories",
        "category": "Academic",
        "image": 1,
        "home": False,
        "description": rich_html(
            lead="The Christiana High School science fair invites students to present investigations with a hypothesis, a method, results and an honest sentence about what went wrong. Displays will occupy the hall; practical demonstrations that need gas or water will stay in the laboratories under staff control.",
            paras=[
                "Parents and neighbouring schools are welcome in the afternoon. Judges will include staff and at least one guest with a scientific job that is not teaching. Students should be ready to explain their work without reading the board word for word.",
            ],
            more=[
                "Projects linked to the environmental awareness initiative are encouraged but not required. Safety goggles are not a costume. Mr. Sean Patterson and Mr. Rohan Barrett will inspect any display that looks like it might stain the floor of history.",
                "The fair is a teaching event. A neat poster with no data will lose to a messy logbook with a real question. That standard is how Christiana High School keeps science from becoming arts and crafts with a beaker.",
                "Winners will be named at a short closing. All participants will pack up. The hall has a concert the following week and cannot remain a rainforest of cardboard overnight.",
            ],
        ),
    },
    {
        "slug": "heritage-week-exhibition",
        "title": "Heritage Week Exhibition",
        "date": "2026-10-12",
        "start": "8:30 a.m.", "end": "3:00 p.m.",
        "venue": "School hall",
        "category": "Holidays",
        "image": 11,
        "home": False,
        "description": event_desc([
            "Heritage Week at Christiana High School will open with an exhibition of student research on community history, independence, language and the arts. Classes will visit on a rota. The public may view displays after 1:30 p.m.",
            "Mr. Kemar Grant asks that captions be written in complete sentences. A printed flag is not a project.",
        ]),
    },
    {
        "slug": "christmas-concert",
        "title": "Christmas Concert",
        "date": "2026-12-11",
        "start": "6:00 p.m.", "end": "8:30 p.m.",
        "venue": "School hall",
        "category": "Student activities",
        "image": 26,
        "home": True,
        "description": event_desc([
            "The performing arts department presents the Christmas concert, with choir, drama and the usual miracle of a piano that stays in tune until the last carol. Tickets will be sold at the office.",
            "Doors open at 5:30 p.m. Children in the audience should be able to sit through a programme. Phones should be dark. The collection at the end will support a student welfare fund.",
        ]),
    },
    {
        "slug": "mid-term-examinations",
        "title": "Mid-Term Examinations",
        "date": "2026-10-05",
        "start": "8:30 a.m.", "end": "3:00 p.m.",
        "venue": "Hall and classrooms",
        "category": "Examinations",
        "image": 29,
        "home": False,
        "description": event_desc([
            "Mid-term examinations will run according to the published timetable. Students must arrive in full uniform with the required stationery. Phones are not allowed in examination rooms.",
            "Absences require a parent call before the paper begins. The school will not invent a special sitting for a child who went to town.",
        ]),
    },
    {
        "slug": "student-council-elections",
        "title": "Student Council Elections",
        "date": "2026-08-21",
        "start": "10:00 a.m.", "end": "2:00 p.m.",
        "venue": "Form rooms and hall",
        "category": "Student activities",
        "image": 42,
        "home": False,
        "description": event_desc([
            "Christiana High School will hold student council elections with speeches in the morning and balloting by form in the afternoon. Campaign materials must come down before voting starts.",
            "Candidates were vetted for attendance and conduct. The count will be observed by staff and by two students who are not on any slate. Results will be announced before dismissal.",
        ]),
    },
    {
        "slug": "grade-11-csec-seminar",
        "title": "Grade 11 CSEC Seminar",
        "date": "2026-10-15",
        "start": "1:00 p.m.", "end": "3:30 p.m.",
        "venue": "School hall",
        "category": "Examinations",
        "image": 29,
        "home": False,
        "description": event_desc([
            "Grade 11 candidates will attend a CSEC seminar covering examination rules, SBA deadlines, and a subject-by-subject reminder of what still has to be done. The seminar shares a date with parent-teacher consultation and the mathematics workshop.",
            "Bring the candidate’s subject list. Parents who are already on campus for consultation may sit at the back for the first half-hour.",
        ]),
    },
    {
        "slug": "technology-club-showcase",
        "title": "Technology Club Showcase",
        "date": "2026-11-20",
        "start": "11:00 a.m.", "end": "2:00 p.m.",
        "venue": "Computer laboratory and hall foyer",
        "category": "Student activities",
        "image": 19,
        "home": False,
        "description": event_desc([
            "The technology club will show student work from the digital skills initiative: documents, simple data charts, posters and a short campus film. Visitors may try a beginner task on spare machines.",
            "Mr. Johnson asks that nobody ‘fix’ a demonstration computer. The showcase is a class with an audience, not a repair shop.",
        ]),
    },
    {
        "slug": "graduation-ceremony",
        "title": "Graduation Ceremony",
        "date": "2026-07-02",
        "start": "10:00 a.m.", "end": "1:00 p.m.",
        "venue": "School hall",
        "category": "Graduation",
        "image": 9,
        "home": False,
        "description": rich_html(
            lead="Graduation at Christiana High School is a formal ceremony for students who have completed the published requirements. Families will hear names read, watch a procession that always takes longer than the rehearsal, and sit through speeches that try to be shorter than the heat.",
            paras=[
                "Graduands must attend rehearsal. Guests should arrive early. The school cannot reserve infinite seats for cousins who decided that morning. Dress for graduands is as published by the office; this is not a fashion show with a hymn.",
            ],
            more=[
                "The Principal will address the class. A student speaker will be chosen for sense as well as fluency. Awards that belong to prize-giving will not all be repeated; the two ceremonies are neighbours, not twins.",
                "Photography will be allowed at designated moments. Walking into the aisle during a name is a good way to become a story the staff tell for years. Christiana High School would like the day to honour work already done, not to invent a celebrity.",
                "After the ceremony, families may take photographs on the grounds. Classrooms will be closed. The canteen may sell drinks. Graduands remain ambassadors of the school in town that afternoon; the uniform or gown still carries the crest.",
                "Rehearsal the day before is compulsory. A student who misses rehearsal may still collect a certificate and may not process. That rule exists because a ceremony is a piece of theatre that honour requires to run on time. Names will be read as they appear on the official list. Corrections must arrive at the office before the published deadline, not at the microphone.",
                "The hall will be warm. Programmes will be few. Guests are asked to stand for the procession and to remain until the last name, even if their child was early on the list. Christiana High School graduates in public because education in this town has always been a family achievement, and because the crest deserves a proper goodbye.",
            ],
        ),
    },
    {
        "slug": "prize-giving-ceremony",
        "title": "Prize-Giving Ceremony",
        "date": "2026-07-03",
        "start": "10:00 a.m.", "end": "1:30 p.m.",
        "venue": "School hall",
        "category": "Graduation",
        "image": 10,
        "home": False,
        "description": event_desc([
            "Prize-giving recognises academic work, leadership, service and selected extra-curricular distinction. Students named in the programme should sit where ushers place them. Applause should end while the next child is still walking.",
            "Parents of award winners are especially welcome. The afternoon is long; the names are the point.",
        ]),
    },
    {
        "slug": "environmental-awareness-day",
        "title": "Environmental Awareness Day",
        "date": "2026-04-22",
        "start": "8:30 a.m.", "end": "2:00 p.m.",
        "venue": "Campus and garden",
        "category": "Student activities",
        "image": 17,
        "home": False,
        "description": event_desc([
            "Environmental Awareness Day includes a campus waste audit, garden work, and short class presentations from the science project. Wear closed shoes. Bring a water bottle.",
            "The day ends with a briefing on what the measurements actually showed. Slogans without numbers will be gently mocked by Mrs. Thompson.",
        ]),
    },
    {
        "slug": "end-of-year-school-celebration",
        "title": "End-of-Year School Celebration",
        "date": "2026-12-18",
        "start": "11:00 a.m.", "end": "2:00 p.m.",
        "venue": "Assembly ground",
        "category": "Student activities",
        "image": 15,
        "home": False,
        "description": event_desc([
            "The end-of-year celebration gathers houses for music, short performances and the last attendance marks of the term. It is not a street dance. Uniform rules relax only as published.",
            "Reports follow on the date given in the office letter. Students should return library books before they attempt to celebrate.",
        ]),
    },
]


assert len(EVENTS) == 20
assert sum(1 for e in EVENTS if e["date"] == "2026-10-15") == 3
assert any(len(e["title"]) > 80 for e in EVENTS)
assert any(len(n["title"]) > 100 for n in NEWS)
assert word_count(next(n["content"] for n in NEWS if n["slug"].startswith("christiana-high-recognises"))) >= 1000
