export const THEME_PRESETS = [
  {
    id: 'classic',
    label: 'Classic',
    description: 'Traditional school site with a strong header and gold accents.',
    headingFont: 'Montserrat',
    bodyFont: 'Inter',
    heroStyle: 'full-image',
    navbarStyle: 'classic',
    newsLayout: 'featured',
    eventsLayout: 'cards',
    footerStyle: 'classic',
    radius: '0.5rem',
    primaryColor: '#0B3D2E',
    secondaryColor: '#FFD100',
    accentColor: '#145C45',
  },
  {
    id: 'modern',
    label: 'Modern',
    description: 'Clean, spacious layout with rounded surfaces and contemporary type.',
    headingFont: 'Outfit',
    bodyFont: 'Inter',
    heroStyle: 'split',
    navbarStyle: 'modern',
    newsLayout: 'cards',
    eventsLayout: 'cards',
    footerStyle: 'modern',
    radius: '1rem',
    primaryColor: '#0F766E',
    secondaryColor: '#F4D58D',
    accentColor: '#115E59',
  },
  {
    id: 'academic',
    label: 'Academic',
    description: 'Serif headings and a formal, university-inspired tone.',
    headingFont: 'Merriweather',
    bodyFont: 'Source Sans 3',
    heroStyle: 'split',
    navbarStyle: 'classic',
    newsLayout: 'grid',
    eventsLayout: 'list',
    footerStyle: 'classic',
    radius: '0.25rem',
    primaryColor: '#1E3A5F',
    secondaryColor: '#B42318',
    accentColor: '#2B4C7E',
  },
  {
    id: 'heritage',
    label: 'Heritage',
    description: 'Editorial, crest-led presentation: serif headings, gold rules, and structured dark/cream sections.',
    headingFont: 'Playfair Display',
    bodyFont: 'Inter',
    heroStyle: 'cinematic',
    navbarStyle: 'heritage',
    newsLayout: 'editorial',
    eventsLayout: 'date-list',
    footerStyle: 'heritage',
    radius: '0.125rem',
    primaryColor: '#241A00',
    secondaryColor: '#FFD400',
    accentColor: '#4A3500',
  },
  {
    id: 'minimal',
    label: 'Minimal',
    description: 'Quiet type, flat colour, and generous whitespace.',
    headingFont: 'DM Sans',
    bodyFont: 'DM Sans',
    heroStyle: 'compact',
    navbarStyle: 'floating',
    newsLayout: 'list',
    eventsLayout: 'cards',
    footerStyle: 'minimal',
    radius: '0.75rem',
    primaryColor: '#123A73',
    secondaryColor: '#C8102E',
    accentColor: '#1D4E89',
  },
  {
    id: 'sky',
    label: 'Sky',
    description: 'Light navigation, cyan accents, and a modern campus look on white and soft blue.',
    headingFont: 'Outfit',
    bodyFont: 'Inter',
    heroStyle: 'spotlight',
    navbarStyle: 'light',
    newsLayout: 'featured',
    eventsLayout: 'list',
    footerStyle: 'structured',
    radius: '0.75rem',
    primaryColor: '#073B52',
    secondaryColor: '#53C7E8',
    accentColor: '#167EA5',
  },
] as const

export const FONT_OPTIONS = [
  'Montserrat',
  'Inter',
  'Outfit',
  'Merriweather',
  'Source Sans 3',
  'Playfair Display',
  'Lora',
  'DM Sans',
  'Cinzel',
  'Libre Baskerville',
] as const

export type ThemeId = (typeof THEME_PRESETS)[number]['id']

export function getThemePreset(id: string | null | undefined) {
  return THEME_PRESETS.find((theme) => theme.id === id) ?? THEME_PRESETS[0]
}
